[build]
builder = "nixpacks"

[build.watchPatterns]
include = ["**/*.{ts,tsx,js,jsx,json,prisma}"]
exclude = [
  "test-*.js", 
  "test-dynamic-fuel-pricing.js",
  "*.md", 
  "*.log", 
  "scripts/", 
  "*.txt", 
  "*.pdf",
  "node_modules/**",
  ".git/**",
  ".next/**"
]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Force clean build
[build.env]
NIXPACKS_NO_CACHE = "1"
NODE_ENV = "production" 