[build]
builder = "nixpacks"
watchPatterns = ["**/*.{ts,tsx,js,jsx,json,prisma}"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Force clean build
[build.env]
NIXPACKS_NO_CACHE = "1"
NODE_ENV = "production" 